agileProject/urls.py
from django.contrib import admin
from django.urls import path, include
import dbApp

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("userApp.urls")),
    path("login/",include("loginApp.urls")),
]

userApp/urls.py
from django.urls import path
from . import views

app_name = 'userApp'

urlpatterns = [
    path('', views.index, name="index"),
    path("knesetyChurches/", views.knesetyChurches, name="knesetyChurches"),
    path('onlineDonation/', views.onlineDonation, name='onlineDonation'),
    path('inPersonDonation/', views.inPersonDonation, name='inPersonDonation'),
    path('adminInv/', views.adminInvPage, name='adminInvPage'),
    path('adminPeopleIN/', views.adminPeopleINPage, name='adminPeopleIN'),
    path('adminReservation/', views.adminReservation, name='adminReservation'),
    path('Giveout/', views.Giveout, name='Giveout'),
    path('myAccountSubmit/', views.myAccountSubmit, name='myAccountSubmit'),
    path('addAdminSubmit/', views.addAdminSubmit, name='addAdminSubmit'),
    path('addpeopleinneedSubmit/', views.addpeopleinneedSubmit, name='addpeopleinneedSubmit'),
    path('inventorySubmit/', views.inventorySubmit, name='inventorySubmit'),
    path('Myaccount/', views.myAccount, name='myAccount'),
]

userApp/models.py
from django.db import models


# Create your models here.

userApp/views.py
from datetime import datetime
from django.http import FileResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from dbApp import models
from Util import *

# Render the inventory dashboard
def adminInvPage(request):
    clearAlert(request)
    try:
        # Get stored data needed for inventory dashborad
        id = getId(request)
        user = getUser(id)
        church = getAdminChurch(id)
        all_items = getItemDetailsFiltered(church)
        l = len(all_items)
        itemsdetails = zip(list(range(1, l+1)), all_items)
        donors = getAllDonors()
        items = getAllItems()
        dict = {'user':user, 'church': church, 'itemsdetails': itemsdetails, 'sz': l, 'items':items, 'donors':donors}
    except:
        return redirect('userApp:index')
    return render(request, "userApp/admininv.html",dict)

# Render people in need dashboadrd
def adminPeopleINPage(request):
    clearAlert(request)
    try:
        # Get stored data needed for people in need dashborad
        id = getId(request)
        user = getUser(id)
        church = getAdminChurch(id)
        all_needs = getNeedsFiltered(church)
        items = getAllItems()
        people = getAllPeopleInNeed()
        l = len(all_needs)
        needs = zip(list(range(1, l+1)), all_needs)
        today = datetime.today().date()
        dict = {'user':user, 'church': church, 'needs': needs, 'today':today, 'sz': l, 'items':items, 'people':people}
    except:
        return redirect('userApp:index')
    return render(request, "userApp/adminPeopleIN.html",dict)

# Render reservation dashboard
def adminReservation(request):
    clearAlert(request)
    try:
        # Get stored data needed for reservation dashborad
        id = getId(request)
        user = getUser(id)
        church = getAdminChurch(id)
        all_reservations = getAllReservationsFiltered(church)
        l = len(all_reservations)
        reservations = zip(list(range(1, l+1)), all_reservations)
        today = datetime.today().date()
        dict = {'user':user, 'church': church, 'reservations': reservations, 'today':today, 'sz': l}
    except:
        return redirect('userApp:index')
    return render(request, "userApp/adminreservation.html",dict)

# Render home page
def index(request):
    clearAlert(request)
    try:
        id = getId(request)
        user = getUser(id)
        # Get data needed for Donor home page
        if user.role.role_name == 'Donor':
            churches = getAllChurches()
            cards = getCardsFiltered(id)
            ts = getAllTimeSlots(30)
            dict = {'user':user, 'churches': churches, 'cards': cards, 'timeslots': ts}

        # Get data needed for Admin home page
        elif user.role.role_name == 'Admin':
            church = getAdminChurch(id)
            today = datetime.today().date()
            all_items = getItemDetailsFiltered(church)
            all_needs = getNeedsFiltered(church)
            all_reservations = getAllReservationsFiltered(church)
            items = zip(list(range(1, min(5, len(all_items)) + 1)), all_items)
            needs = zip(list(range(1, min(5, len(all_needs)) + 1)), all_needs)
            reservations = zip(list(range(1, min(5, len(all_reservations)) + 1)), all_reservations)
            dict = {'user':user, 'church': church, 'items': items,'needs': needs, 'reservations': reservations, 'today': today, 'sz1': len(all_needs), 'sz2': len(all_items), 'sz3': len(all_reservations)}
        else:
            raise KeyError()
    except:
        dict = {'role' : "Anon", 'name': "", 'rolenum': -1}
    return render(request, "userApp/index.html", dict) 

# Action taken when giveout button is clicked in people in need dashboard
def Giveout(request):
    selected_need = request.POST.get('Giveout')
    need = models.Need.objects.get(id = selected_need)
    church = need.church_id
    item = need.item_id
    if not saveItemDetailsGiveout(church, item, need):
        makeAlert(request, 1, "Can't Giveout This Item")
        return redirect('userApp:adminPeopleIN')
    needDueDateAlter(need)
    makeAlert(request, 2, "Giveout Done")
    return redirect('userApp:index')

# Donor online cash donation
def onlineDonation(request):
    id = getId(request)
    amount = request.POST['Amount']
    selected_card = request.POST.get('card_dropdown')
    church = int(request.POST.get('church_dropdown'))
    # Error not selecting a church
    if church == 0:
        makeAlert(request, 1, "Please Select a Church")
        return redirect('userApp:index')
    # Use new card
    church = getChurch(church)
    if selected_card == '0':
        # Get data from view
        cardNumber = request.POST['Cardnum']
        holderName = request.POST['Cardholdname']
        CVV = int(request.POST['CVV'])
        expiryDate = request.POST['Expiry']   
        expiryDate = datetime.strptime(expiryDate, '%Y-%m').date()
        try:
            save = request.POST['saveCard']
        except:
            save = ''
        # Chech credentials
        if not checkOnlineDonation(cardNumber, CVV, expiryDate):
            # Credentials Error
            makeAlert(request, 1, "Enter Valid Card Info")
            return redirect('userApp:index')
        # Save card
        if save == 'on':
            saveCard(id, cardNumber, CVV, expiryDate)
    # Prepare data to be stored
    amount = toInt(amount)
    item = getItemByName('Cash')
    donor = getDonor(id)
    # Store data in database
    r_details =  saveReciept(donor, church, item, amount)
    saveItemDetails(church, item, amount)
    makeAlert(request, 2, "Thank you for your generous donation, Receipt started downloading")
    generateReceipt(request, r_details)
    return redirect('userApp:index')

# Reserve in-person meeting for donation
def inPersonDonation(request):
    id = request.COOKIES['userid']
    # Get data from view
    selected_church = int(request.POST.get('church_dropdown2'))
    selected_timeslot = request.POST.get('timeslot_dropdown')
    meeting_date = request.POST['meeting_date']
    # Error not selecting a church
    if selected_church == 0:
        makeAlert(request, 1, "Please Select a Church")
        return redirect('userApp:index')
    # No timeslot seleceted
    if selected_timeslot == '0':
        makeAlert(request, 1, 'Please select a timeslot')
        return redirect('userApp:index')
    # Try to save reservation
    ret = saveReservation(id, selected_church, meeting_date, selected_timeslot)
    # Reservation Error
    if ret != 0:
        # No church selected error
        if ret == 1:
            makeAlert(request, 1, "Please Select a church")
        # No date selected error
        if ret == 2:
            makeAlert(request, 1, "Plase Select Appropriate Date")
        # Already reserved date and time for the church error
        if ret == 3:
            makeAlert(request, 1, "Already Reserved")
        return redirect('userApp:index')
    # Reservation completed
    makeAlert(request, 2, "Reservation Done")  
    return redirect('userApp:index')

def myAccount(request):
    clearAlert(request)
    id = getId(request)
    user = getUser(id)
    if user.role.role_number == 1:
        church = getAdminChurch(id)
        churches = getAllChurchesExcept(church.church_id)
        items = getAllItems()
        people = getAllPeopleInNeed()
        donors = getAllDonors()
        dict = {'user':user, 'church': church, 'churches':churches, 'items':items, 'people':people, 'donors': donors}
    elif user.role.role_number == 2:
        dict = {'user':user}
    return render(request, "userApp/Myaccount.html", dict)

def myAccountSubmit(request):
    id = getId(request)
    user = getUser(id)
    name = request.POST['Name']
    password = request.POST['Password']
    if name != '':
        user.name = name
    if password != '':
        user.password = password
    user.save()
    return HttpResponseRedirect('/')

def addAdminSubmit(request):
    id = getId(request)
    email = request.POST['Email']
    emails = getAllEmailsFiltered(email)
    if len(emails) > 0:
        makeAlert(request, 1, 'Email is registered before')
        return redirect('userApp:myAccount')
    name = request.POST['Name']
    church = getAdminChurch(id)
    saveUser(name, email, 'Admin', 'Admin', church)
    return HttpResponseRedirect('/')

def addpeopleinneedSubmit(request):
    id = getId(request)
    person = request.POST.get('people_dropdown')
    item = request.POST['item_datalist1']
    quantity = request.POST['Quantity1']
    period = request.POST['Period']
    date = request.POST['due_date']
    church = getAdminChurch(id)
    if person == '-1':
        name = request.POST['person_name']
        ID = request.POST['person_ID']
        if name == '':
            makeAlert(request, 1, 'Specify Person in Need Name')
            return redirect('userApp:myAccount')
        if ID == '':
            makeAlert(request, 1, 'Specify Person in Need National ID')
            return redirect('userApp:myAccount')
        person = models.PeopleInNeed(id = ID, name = name)
        person.save()
    elif person == '0':
        makeAlert(request, 1, 'Please Choose a Person in Need or Add New One')
        return redirect('userApp:myAccount')
    else:
        person = getPeopleInNeed(person)
    if date == '':
        makeAlert(request, 1, 'Specify a Date')
        return redirect('userApp:myAccount')
    if item == '':
        makeAlert(request, 1, 'Specify an Item')
        return redirect('userApp:myAccount')
    if quantity == '':
        makeAlert(request, 1, 'Specify a Quantity')
        return redirect('userApp:myAccount')
    if period == '':
        makeAlert(request, 1, 'Specify a Period')
        return redirect('userApp:myAccount')
    date = datetime.strptime(date, '%Y-%m-%d').date()
    item = getItemByName(item)
    changeSaveNeed(church, item, person, quantity, date, period)
    return HttpResponseRedirect('/')

templates/userApp/Myaccount.html
{% extends 'base.html' %}

{% block navbar %} 

{% include 'navbar.html' with prole=user.role.role_name %}

{% endblock navbar %}

{% block content %}

{% if request.session.alert == 1 %}
<br>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{request.session.message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
</div>

{% elif request.session.alert == 2 %}
<br>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{request.session.message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
</div>
{% endif %}

<div style="display: flex; width: 100%; height: 90%">
    <div style="
      margin-left: auto;
      margin-right: auto;
      margin-top: auto;
      margin-bottom: auto;
    " class="position-relative">
        <h3>Your Account Details:</h3>
        <form action="{% url 'userApp:myAccountSubmit' %}" method="post">
            {% csrf_token %}
            <div class="row mb-3">
                <label for="colFormLabel" class="col-form-label">Your Email:</label>
                <div class="col-sm-10">
                    <input type="Email" name="Email" class="form-control" id="colFormLabel" value='{{user.email}}' readonly/>
                </div>
                <label for="colFormLabel" class="col-form-label">Your Name:</label>
                <div class="col-sm-10">
                    <input type="Text" name="Name" class="form-control" id="colFormLabel" placeholder='{{user.name}}'/>
                </div>
                <label for="colFormLabel" class="col-form-label">Change Your Password:</label>
                <div class="col-sm-10">
                    <input name="Password" type="Password" class="form-control" id="colFormLabel" />
                </div>
            </div>
            <input type="submit" class="btn btn-primary" value="Update Information" />
        </form>
    

{% if user.role.role_name == 'Admin' %}

<button type="button" class="btn btn-primary position-absolute end-0" data-toggle="modal" data-target="#adminModal">Add Admin</button>


<form action="{% url 'userApp:addAdminSubmit' %}" method="post">
    {% csrf_token %}
    <div class="modal fade" id="adminModal" role="dialog">
        <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
            <h4 class="modal-title">Add User</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
            <div style="display: flex; width: 100%; height: 90%">
            <div style="
            margin-left: auto;
            margin-right: auto;
            margin-top: auto;
            margin-bottom: auto;
            " class="position-relative">
                    <div class="row mb-3">
                        <label for="colFormLabel" class="col-form-label">Email:</label>
                        <div class="col-sm-10">
                            <input type="Email" name="Email" class="form-control" id="colFormLabel" placeholder="example@example.com" />
                        </div>
                        <label for="colFormLabel" class="col-form-label">Name:</label>
                        <div class="col-sm-10">
                            <input type="Text" name="Name" class="form-control" id="colFormLabel" placeholder="Your Name" />
                        </div>
                    </div>
                        <input type="submit" class="btn btn-primary" value="Add Admin"/>
            </div>
            </div>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        </div>
    </div>
</form>

<br>
<br>
{% endif %}

</div>
</div>


{% endblock content %}

templates/userApp/admininv.html
{% extends 'base.html' %}

{% block navbar %} 

{% include 'navbar.html' with prole=user.role.role_name %}

{% endblock navbar %}


{% block content %}


{% if request.session.alert == 1 %}
<br>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{request.session.message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
</div>

{% elif request.session.alert == 2 %}
<br>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{request.session.message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
</div>
{% endif %}
<br>
{% if  user.role.role_name == 'Admin' %} {% comment %} Admin {% endcomment %}
<table id="example" class="table table-striped" style="width:100%">
    <thead>
        <tr>
            <th scope="col" style="width: 15%">#</th>
            <th scope="col" style="width: 35%">Church</th>
            <th scope="col" style="width: 25%">Item</th>
            <th scope="col" style="width: 25%">Quantity</th>
        </tr>
    </thead>
    <tbody>
        {% if sz == 0 %}
        <tr>
            <td colspan="4" style='text-align: center'>No items in inventory to be shown</td>
            <td hidden></td>
            <td hidden></td>
            <td hidden></td>
        </tr>
        {% else %}
            {% for i, item in itemsdetails  %}
            <tr>
                <th scope="row">{{i}}</th>
                <td>{{church.name}}</td>
                <td>{{item.item_id.name}}</td>
                <td>{{item.quantity}}</td>
            </tr>
            {%endfor%}
        {% endif %}
    </tbody>
</table>

<br>
<br>
<button type="button" class="btn btn-primary position-absolute end-0" data-toggle="modal" data-target="#inventoryModal">Add to Inventory</button>

<form action="{% url 'userApp:inventorySubmit' %}" method="post">
    {% csrf_token %}
    <div class="modal fade" id="inventoryModal" role="dialog">
        <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
            <h4 class="modal-title">Add to Inventory</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
            <div style="display: flex; width: 100%; height: 90%">
            <div style="
            margin-left: auto;
            margin-right: auto;
            margin-top: auto;
            margin-bottom: auto;
            " class="position-relative">
                    <div class="row mb-3">
                        <label for="colFormLabel" class="col-form-label">Donor</label>
                        <div class="col-sm-10">
                            <input type="text" class='form-control' placeholder="Search.." id="search_donor" onkeyup="filterFunction()">
                            <select name="donor_dropdown" class="form-control" id='donor_dropdown' onchange='showitemsinventory(this)'>
                                <option value="0" selected="selected">Please select a Donor</option>
                                {% for donor in donors %}
                                <option value="{{donor.user_id.user_id}}">{{donor.user_id.name}} ({{donor.user_id.email}})</option>
                                {% endfor%}
                                <option style="font-size: 1pt; background-color: #555555;" disabled value='-1'>&nbsp;</option>
                                <option value="-1">Other</option>
                            </select>
                        </div>
                        <div id='data_hidden_inventory' style="display: none">
                            <div class="col-sm-10">
                                <label for="colFormLabel" class="col-form-label">Donor Name:</label>
                                <input type="text" name="donor_name" class="form-control"  placeholder="Name"/>
                            </div>
                            <div class="col-sm-10">
                                <label for="colFormLabel" class="col-form-label">Donor Email:</label>
                                <input type="text" name="donor_email" class="form-control" placeholder="National ID" />
                            </div>
                        </div>
                        <script>

                            function showitemsinventory(select) {
                                if (select.value == "-1") {
                                    document.getElementById('data_hidden_inventory').style.display = 'block';
                                }
                                else{
                                    document.getElementById('data_hidden_inventory').style.display = 'none';
                                }
                            }
                                                        
                            function filterFunction() {
                              var input, filter, ul, li, a, i;
                              input = document.getElementById("search_donor");
                              filter = input.value.toUpperCase();
                              div = document.getElementById("donor_dropdown");
                              a = div.getElementsByTagName("option");
                              for (i = 0; i < a.length; i++) {
                                txtValue = a[i].textContent || a[i].innerText;
                                if (txtValue.toUpperCase().indexOf(filter) > -1 || a[i].value == '-1') {
                                  a[i].style.display = "";
                                } else {
                                  a[i].style.display = "none";
                                }
                              }
                            }
                            </script>
                        <label for="colFormLabel" class="col-form-label">Item:</label>
                        <div class="col-sm-10" >
                                <input list="browsers" name="item_datalist2" class='form-control' placeholder='Search..'/>
                                <datalist id="browsers" >
                                    {% for item in items %}
                                    <option value="{{item.name}}">
                                    {% endfor%}
                                </datalist>
                        </div>
                        <label for="colFormLabel" class="col-form-label">Quantity:</label>
                        <div class="col-sm-10">
                            <input type="number" name="Quantity2" class="form-control" id="colFormLabel" placeholder="Quantity" />
                        </div>
                        
                    </div>
                        <input type="submit" class="btn btn-primary" value="Add to Inventory"/>
                    </div>
            </div>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        </div>
    </div>
</form>
<br>
<br>

{% endif %}

{% endblock content %}

templates/userApp/adminpeoplein.html
{% extends 'base.html' %}

{% block navbar %} 

{% include 'navbar.html' with prole=user.role.role_name %}

{% endblock navbar %}


{% block content %}

{% if request.session.alert == 1 %}
<br>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{request.session.message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
</div>

{% elif request.session.alert == 2 %}
<br>
<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{request.session.message}}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
</div>
{% endif %}

<br>

{% if  user.role.role_name == 'Admin' %} {% comment %} Admin {% endcomment %}
<table id="example" class="table table-hover" style="width:100%">
    <thead>
        <tr>
            <th scope="col" style="width: 10%">#</th>
            <th scope="col" style="width: 18%">Person in Need</th>
            <th scope="col" style="width: 18%">Item</th>
            <th scope="col" style="width: 18%">Quantity</th>
            <th scope="col" style="width: 18%">Due Date</th>
            <th scope="col" style="width: 18%">Giveout</th>
        </tr>
    </thead>
    <tbody>
        {% if sz == 0 %}
        <tr>
            <td colspan="6" style='text-align: center'>No people in need to be shown</td>
            <td hidden></td>
            <td hidden></td>
            <td hidden></td>
            <td hidden></td>
            <td hidden></td>
        </tr>
        {% else %}
            {% for i, need in needs%}
            {% if today > need.due_date %}

                <tr class="p-3 mb-2 bg-danger text-white">

                {% elif today == need.due_date %}

                <tr class="p-3 mb-2 bg-warning text-dark">

                {% else %}

                <tr>

                {% endif %}
                <th scope="row">{{i}}</th>
                <td>{{need.people_in_need_id.name}}, ID: {{need.people_in_need_id.id}}</td>
                <td>{{need.item_id.name}}</td>
                <td>{{need.quantity}}</td>
                <td>{{need.due_date}}</td>
                {% comment %} <td><input type="submit" class="btn btn-block btn-info" value={{need.id}} />Give out</td> {% endcomment %}
                <td> 
                    <div>
                        <form action="{% url 'userApp:Giveout' %}" method="post">
                        {% csrf_token %}
                        <input name="Giveout" class="d-none" value='{{need.id}}' >
                        <input class="btn btn-block btn-info" type="submit" value="Give out">
                        </form>
                    </div>
                    
            </tr>
            {%endfor%}
            {% endif %}
    </tbody>
</table>

<br>
<br>
<button type="button" class="btn btn-primary position-absolute end-0" data-toggle="modal" data-target="#peopleinneedModal">Add People in need</button>


<form action="{% url 'userApp:addpeopleinneedSubmit' %}" method="post">
    {% csrf_token %}
    <div class="modal fade" id="peopleinneedModal" role="dialog">
        <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
            <h4 class="modal-title">Add Person in Need</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
            <div style="display: flex; width: 100%; height: 90%">
            <div style="
            margin-left: auto;
            margin-right: auto;
            margin-top: auto;
            margin-bottom: auto;
            " class="position-relative">
                    <div class="row mb-3">
                        <label for="colFormLabel" class="col-form-label">Person in Need:</label>
                        <div class="col-sm-10">
                            <input type="text" class='form-control' placeholder="Search.." id="search_people" onkeyup="filterFunction1()">
                            <select name="people_dropdown" class="form-control" id='people_dropdown' onchange='showitemspeople(this)'>
                                <option value="0" selected="selected">Please select a Person</option>
                                {% for person in people %}
                                <option value="{{person.id}}">{{person.name}}, ID = {{person.id}}</option>
                                {% endfor%}
                                <option style="font-size: 1pt; background-color: #555555;" disabled value='-1'>&nbsp;</option>
                                <option value="-1">Other</option>
                            </select>
                        </div>
                        <div id='data_hidden_peopleinneed' style="display: none">
                            <div class="col-sm-10">
                                <label for="colFormLabel" class="col-form-label">Person Name:</label>
                                <input type="text" name="person_name" class="form-control"  placeholder="Name"/>
                            </div>
                            <div class="col-sm-10">
                                <label for="colFormLabel" class="col-form-label">Person National ID:</label>
                                <input type="text" name="person_ID" class="form-control" placeholder="National ID" />
                            </div>
                        </div>
                        <script>

                            function showitemspeople(select) {
                                if (select.value == "-1") {
                                    document.getElementById('data_hidden_peopleinneed').style.display = 'block';
                                }
                                else{
                                    document.getElementById('data_hidden_peopleinneed').style.display = 'none';
                                }
                            }
                                                        
                            function filterFunction1() {
                              var input, filter, ul, li, a, i;
                              input = document.getElementById("search_people");
                              filter = input.value.toUpperCase();
                              div = document.getElementById("people_dropdown");
                              a = div.getElementsByTagName("option");
                              for (i = 0; i < a.length; i++) {
                                txtValue = a[i].textContent || a[i].innerText;
                                if (txtValue.toUpperCase().indexOf(filter) > -1 || a[i].value == '-1') {
                                  a[i].style.display = "";
                                } else {
                                  a[i].style.display = "none";
                                }
                              }
                            }
                            </script>
                        <label for="colFormLabel" class="col-form-label">Item:</label>
                        <div class="col-sm-10" >
                                <input list="browsers" name="item_datalist1" class='form-control' placeholder='Search..'/>
                                <datalist id="browsers" >
                                    {% for item in items %}
                                    <option value="{{item.name}}">
                                    {% endfor%}
                                </datalist>
                        </div>
                        <label for="colFormLabel" class="col-form-label">Quantity:</label>
                        <div class="col-sm-10">
                            <input type="number" name="Quantity1" class="form-control" id="colFormLabel" placeholder="Quantity" />
                        </div>
                        <label for="colFormLabel" class="col-form-label">Period in Days:</label>
                        <div class="col-sm-10">
                            <input type="number" name="Period" class="form-control" id="colFormLabel" placeholder="Period" />
                        </div>
                        <label for="colFormLabel" class="col-form-label">Due Date:</label>
                        <div class="col-sm-10">
                            <input type="date" name="due_date" class="form-control" id="colFormLabel" placeholder="YYYY-MM-DD" />
                        </div>
                    </div>
                        <input type="submit" class="btn btn-primary" value="Add Person in Need"/>
                    </div>
            </div>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        </div>
    </div>
</form>
<br><br>

{% endif %}


{% endblock content %}