agileProject/urls.py
from django.contrib import admin
from django.urls import path, include
import dbApp

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("userApp.urls")),
    path("login/",include("loginApp.urls")),
]

userApp/urls.py
from django.urls import path
from . import views

app_name = 'userApp'

urlpatterns = [
    path('', views.index, name="index"),
    path("knesetyChurches/", views.knesetyChurches, name="knesetyChurches"),
    path('onlineDonation/', views.onlineDonation, name='onlineDonation'),
    path('inPersonDonation/', views.inPersonDonation, name='inPersonDonation'),
    path('adminInv/', views.adminInvPage, name='adminInvPage'),
    path('adminPeopleIN/', views.adminPeopleINPage, name='adminPeopleIN'),
    path('adminReservation/', views.adminReservation, name='adminReservation'),
    path('Giveout/', views.Giveout, name='Giveout'),
    path('myAccountSubmit/', views.myAccountSubmit, name='myAccountSubmit'),
    path('addAdminSubmit/', views.addAdminSubmit, name='addAdminSubmit'),
    path('addpeopleinneedSubmit/', views.addpeopleinneedSubmit, name='addpeopleinneedSubmit'),
    path('inventorySubmit/', views.inventorySubmit, name='inventorySubmit'),
    path('Myaccount/', views.myAccount, name='myAccount'),
]

templates/base.html
{% load bootstrap5 %} {% bootstrap_css %}
{% bootstrap_javascript %} 
{% bootstrap_messages %} 

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.0.272/jspdf.debug.js"></script>
    <script>
      $(document).ready(function () {
        $('#example').DataTable();
    });       
    </script>
</head>

<body>
{% block navbar %} 
{% endblock navbar %}
<div style="margin-left: 0.9%; margin-right: 0.9%" class="position-relative"> 
{% block content %} 
{% endblock content %}
</div>
</body>

templates/navbar.html
{% extends 'base.html' %}
{% block navbar %}

{% if prole == 'Admin' %}


{% include 'navbaradmin.html' %}

{% elif prole == 'Donor' %}

{% include 'navbardonor.html' %}

{% else %}

{% include 'navbarlogin.html' %}


{% endif %}

{% endblock navbar %}

templates/navbaradmin.html
<nav class="navbar sticky-top navbar-expand-xl navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img alt="Home" width="50" height="50" padding="100px" src="https://www.collinsdictionary.com/images/thumb/church_61786270_250.jpg">        
        </a>
        <a class="navbar-brand" href="#">Admin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark" aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse show" id="navbarDark">
            <ul class="navbar-nav me-auto mb-2 mb-xl-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'userApp:knesetyChurches' %}>Kenesty Churches</a>
                </li>
            </ul>
            {% comment %} <a href="/login/donorSignup/">
                <button class="btn btn-outline-light">Sign Up</button>
            </a> {% endcomment %}
            <a href={% url 'userApp:myAccount' %}>
                <button class="btn btn-outline-light">My account</button>
            </a>
            {% comment %} <a href="/login">
                <button class="btn btn-outline-light" type="submit">Login</button>
            </a> {% endcomment %}
            <a href="/login/donorLogout">
                <button class="btn btn-outline-light">Logout</button>
            </a>
        </div>
    </div>
</nav>

templates/navbardonor.html
<nav class="navbar sticky-top navbar-expand-xl navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img alt="Home" width="50" height="50" padding="100px" src="https://www.collinsdictionary.com/images/thumb/church_61786270_250.jpg">        
        </a>
        <a class="navbar-brand" href="#">Donor</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark" aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse show" id="navbarDark">
            <ul class="navbar-nav me-auto mb-2 mb-xl-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'userApp:knesetyChurches' %}>Kenesty Churches</a>
                </li>
            </ul>
            <a href={% url 'userApp:myAccount' %}>
                <button class="btn btn-outline-light">My account</button>
            </a>
            <a href="/login/donorLogout">
                <button class="btn btn-outline-light">Logout</button>
            </a>
        </div>
    </div>
</nav>

templates/navbarlogin.html
<nav class="navbar sticky-top navbar-expand-xl navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img alt="Home" width="50" height="50" padding="100px" src="https://www.collinsdictionary.com/images/thumb/church_61786270_250.jpg">        
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarDark" aria-controls="navbarDark" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <div class="collapse navbar-collapse show" id="navbarDark">
            <ul class="navbar-nav me-auto mb-2 mb-xl-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'userApp:knesetyChurches' %}>Kenesty Churches</a>
                </li>
            </ul>
            <a href="/login/donorSignup/">
                <button class="btn btn-outline-light">Sign Up</button>
            </a>
            {% comment %} <a href="/login/donorMyaccount/">
                <button class="btn btn-outline-light">My account</button> {% endcomment %}
            </a>
            <a href="/login">
                <button class="btn btn-outline-light" type="submit">Login</button>
            </a>
            {% comment %} <a href="/login/donorLogout">
                <button class="btn btn-outline-light">Logout</button>
            </a> {% endcomment %}
        </div>
    </div>
</nav>